export const appRouters = {

    LINK_TO_HOME_PAGE: '',
    LINK_TO_OLD_ANNOUNCEMENT_PAGE: 'announcement',
    LINK_TO_LOGIN_PAGE: 'login',
    LINK_TO_LOGIN_INDEX_PAGE: 'loginPanel',
    LINK_TO_LOGIN_PASSWORD_RESET_PAGE: 'passwordReset',
    LINK_TO_REGISTER_PAGE: 'register',
    LINK_TO_PERSONAL_INFO_PAGE: 'personalInfo',
    // Student
    LINK_TO_MY_TOPIC_PAGE: 'myTopic',
      LINK_TO_STUDENT_TOPIC_DETAIL: 'myTopic/:_id/topicDetail',
      LINK_TO_STUDENT_TOPIC_PRODUCT: 'myTopic/:_id/topicProduct',
      LINK_TO_STUDENT_TOPIC_PAPERS: 'myTopic/:_id/topicPapers',
        LINK_TO_STUDENT_TOPIC_PAPER_CREATION: 'myTopic/:_id/topicPapers/:templateGivenId/topicPaperCreation',
    LINK_TO_REGISTER_TOPIC_PAGE: 'registerTopic',
    LINK_TO_MY_REQUEST_PAGE: 'myRequest',
    LINK_TO_VIEW_TEMPLATES_PAGE: 'templates',
    // Faculty vice dean
    LINK_TO_FVD_EXPENSE_STATISTIC: 'fvdExpenseStatistic',
    LINK_TO_FVD_TOPIC_STATISTIC: 'fvdTopicStatistic',
    LINK_TO_REQUEST_MANAGEMENT: 'requestManagement',
    // Faculty secretary
    LINK_TO_FS_EXPENSE_STATISTIC: 'fsExpenseStatistic',
    LINK_TO_FS_TOPIC_STATISTIC: 'fsTopicStatistic',
    LINK_TO_STUDENT_ACCOUNT_MANAGEMENT: 'studentAccountManagement',
    LINK_TO_VICEDEAN_ACCOUNT_MANAGEMENT: 'vicedeanAccountManagement',
    LINK_TO_PERIOD_MANAGEMENT: 'periodManagement',
    LINK_TO_FS_TOPIC_CONDITION_MANAGEMENT: 'topicCondition',
    LINK_TO_FS_REVIEW_COUNCIL: 'fsReviewCouncil',
    LINK_TO_FS_REVIEW_COUNCIL_DETAIL: 'fsReviewCouncil/:councilId',
    LINK_TO_FS_CREATE_COUNCIL_2: 'fsCreateCouncil2',
    LINK_TO_FS_COUNCIL_2_DETAIL: 'fsCouncil2Detail',
    LINK_TO_FS_ALLOCATE_EXPENSE: 'fsAllocateExpense',
    LINK_TO_FS_TOPIC_MANAGEMENT: 'topicManagement',
      LINK_TO_FS_TOPIC_DETAIL: 'topicManagement/:_id/topicDetail',
      LINK_TO_FS_TOPIC_PRODUCT: 'topicManagement/:_id/topicProduct',
      LINK_TO_FS_TOPIC_PAPERS: 'topicManagement/:_id/topicPapers',
      LINK_TO_FS_RESULT_NOTIFICATION: 'topicManagement/:_id/resultNotification',
      LINK_TO_FS_FEEDBACK: 'topicManagement/:_id/feedback',
    LINK_TO_FS_TEMPLATE_MANAGEMENT: 'templateManagement',
      LINK_TO_FS_FORM_CREATION: 'templateManagement/:_id/formCreation',
      LINK_TO_FS_FORM_UPDATE: 'templateManagement/:_id/formUpdate',
    LINK_TO_FS_UPLOAD_ANNOUNCEMENT: 'fsUploadAnnouncement'
  };
  