export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const RESET_PASSWORD_SUCCESS = "RESET PASSWORD SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET PASSWORD FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_TOPIC_CONDITION = "SET_TOPIC_CONDITION";
export const ADD_EXPR_TOPIC_CONDITION = "ADD_EXPR_TOPIC_CONDITION";
export const UPDATE_EXPR_TOPIC_CONDITION = "UPDATE_EXPR_TOPIC_CONDITION";
export const DELETE_EXPR_TOPIC_CONDITION = "DELETE_EXPR_TOPIC_CONDITION";
export const UPDATE_LEADER_CONDITION = "UPDATE_LEADER_CONDITION";